FROM ubuntu:jammy

ARG DEBIAN_FRONTEND=noninteractive 

RUN apt-get -y update && apt -y install \
    gcc git \
    wget vim curl unzip swig \
    python3-pip cmake automake lsb-release \
    build-essential \
    apt-utils flex bison mona \
    libeigen3-dev \
	gpg-agent
    
# OR-Tools
WORKDIR /root/installation
RUN git clone https://github.com/google/or-tools
WORKDIR /root/installation/or-tools
RUN cmake -S . -B build -DBUILD_DEPS=ON 
#RUN cmake --build build --config Release --target all -j -v
RUN cmake --build build --config Release --target install -v

# Gurobi
ENV GUROBI_HOME=/opt/gurobi1102/linux64
ENV PATH=$GUROBI_HOME/bin:$PATH
ENV LD_LIBRARY_PATH=$GUROBI_HOME/lib:$LD_LIBRARY_PATH
ENV GRB_LICENSE_FILE=/root/berry-er/license_files/gurobi.lic
ENV MOSEKLM_LICENSE_FILE=/root/berry-er/license_files/mosek.lic

RUN wget https://packages.gurobi.com/11.0/gurobi11.0.2_linux64.tar.gz && \
    tar -xvzf gurobi11.0.2_linux64.tar.gz && \
    rm gurobi11.0.2_linux64.tar.gz && \
    mv gurobi1102 /opt/

# cuBLAS
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin && \
    mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb && \
    apt-get update

RUN apt-get install -y \
    cuda-toolkit-12-2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PATH /usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:${LD_LIBRARY_PATH}

# Intel MKL
RUN apt update
RUN wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update
RUN apt install -y intel-oneapi-mkl-devel

# Setup workspace
WORKDIR /root/berry-er

RUN mkdir -p build && rm -r build
RUN mkdir build 

