#pragma once

#include "Problem.h"

#include <set>

namespace BRY {

template <std::size_t DIM>
struct Action {
    /// @brief Apply an action to transform a set, i.e. subdivide, raise the degree
    /// @param old_set Set to apply the transformation to
    /// @param new_sets Container to insert the new sets into
    /// @param normalized_split_point Point at which a set should be split
    /// @return `true` if action succeeded (or is valid for the given set) and `false` otherwise
    virtual bool apply(const HyperRectangle<DIM>& old_set, const Eigen::Vector<bry_float_t, DIM>& normalized_split_point, std::vector<HyperRectangle<DIM>>& new_sets) const = 0;

    virtual ~Action() {}
};

/* Actions that can be used when constructing the adaptive problem */

/// @brief Divide along a given dimension
/// @tparam DIM Dimension of the problem
/// @tparam DIV_DIM Dimension in which the set should be divided
template <std::size_t DIM>
struct Divide : public Action<DIM> {
    Divide(bry_int_t div_dim_) : div_dim(div_dim_) {}

    virtual bool apply(const HyperRectangle<DIM>& old_set, const Eigen::Vector<bry_float_t, DIM>& normalized_split_point, std::vector<HyperRectangle<DIM>>& new_sets) const override;

    bry_int_t div_dim = 0;

    virtual ~Divide() {}
};

/// @brief Increase the bernstein degree of a set
/// @tparam DIM Dimension of the problem
template <std::size_t DIM>
struct IncreaseDegree : public Action<DIM> {
    IncreaseDegree(bry_int_t increase_) : increase(increase_) {}

    virtual bool apply(const HyperRectangle<DIM>& old_set, const Eigen::Vector<bry_float_t, DIM>& normalized_split_point, std::vector<HyperRectangle<DIM>>& new_sets) const override;

    /// @brief Amount to increase the degree by each time the action is applied
    bry_int_t increase = 1;

    virtual ~IncreaseDegree() {}
};

template <std::size_t DIM>
std::vector<Action<DIM>*> makeSubdivisonActions();

template <std::size_t DIM>
class AdaptiveProblem : public PolyDynamicsProblem<DIM> {
    public:
        /// @brief Array of virtual actions (owning) pointers that the algorithm will use. Actions will be deleted on destruction
        std::vector<Action<DIM>*> actions;

        /// @brief Maximum number of constraints in the problem
        bry_int_t max_constraints;

        /// @brief Maximum number of solutions the search algorithms encounters before returning the best one.
        bry_int_t max_ideal_solutions_found = 10;

        /// @brief If not null, adapt the subdivision to the existing barrier up to max_constraints
        const LPSolver::Result* existing_result = nullptr;

        ~AdaptiveProblem();
    public:
        virtual const ConstraintMatrices<DIM> getConstraintMatrices() override;

        void setComparisonTolerance(bry_float_t tol);

        /// @brief Reset all search contents
        void reset();

    private:
        /* TODO */
        ///// @brief Inequality lexicographic comparison in order: 
        ///// 1) bernstein_deg_incr, 2) lower_bounds, 3) upper_bounds
        ///// to within floating point threshold
        //struct HyperRectangleComparator {
        //    bool operator()(const HyperRectangle& lhs, const HyperRectangle& rhs) const;
        //};

        /// @brief Wrapper around HyperRectangle for identifying unique sets
        using Set = std::pair<ConstraintType, HyperRectangle<DIM>>;

        struct SetProperties {
            /// @brief Min robustness across any constraint in the set
            bry_float_t min_robustness = 0.0;

            /// @brief Number of constraints generated by this set
            bry_int_t n_constraints = 0;

            /// @brief Point at which the set should be divided
            Eigen::Vector<bry_float_t, DIM> normalized_split_point;

            bool vertex_condition = false;
        };

        using QSetIt = typename std::map<Set, SetProperties>::iterator;

        /// @brief State comparison for uniqueness (basically ignore the robustness value)
        struct UniquenessQSetItComparator {
            BRY_INL bool operator()(const QSetIt& lhs, const QSetIt& rhs) const {
                //Compare the addresses of each key since they are by defintion unique
                return &(lhs->first) < &(rhs->first); 
            }
        };

        struct State {
            State() = default;

            /// @brief Copy ctor that preserves the iterator validity of `min_robustness_set`
            State(const State& other);

            /// @brief All sets that make up a given state, sorted by pointer value for uniqueness comparison
            std::set<QSetIt, UniquenessQSetItComparator> sets;

            /// @brief Iterator to the set with the minimum robustness. Calculated when state is created, never edited after
            typename std::set<QSetIt>::iterator min_robustness_set;

            /// @brief Min robustness accross any set in the state
            bry_float_t min_robustness;

            /// @brief Number of total constraints to not exceed the threshold
            bry_int_t n_total_constraints;

            /// @brief Iterate through all the sets stored in this state and determine the set with the minimum robustness
            /// that does not meet the vertex condition
            /// @return `true` if succeeded, `false` if all sets had the vertex condition
            bool assignMinRobustnessSet();

            /// @brief Compute the number of total constraints in this state
            void assignNConstraints();
        };

        struct UniquenessHyperrectangleComparator {
            bry_float_t difference_tolerance = 1e-3;

            bool operator()(const HyperRectangle<DIM>& lhs, const HyperRectangle<DIM>& rhs) const {
                // Lexicographical comparison of two vectors
                auto lexLess = [this](const auto& v1, const auto& v2) -> bool {
                    for (bry_int_t i = 0; i < v1.size(); ++i) {
                        if (v1[i] < (v2[i] - difference_tolerance)) {
                            return true;
                        } else if (v1[i] > (v2[i] + difference_tolerance)) {
                            return false;
                        }
                    }
                    return false;
                };

                if (lhs.bernstein_deg_incr < rhs.bernstein_deg_incr) {
                    return true;
                } else if (rhs.bernstein_deg_incr < lhs.bernstein_deg_incr) {
                    return false;
                } else if (lexLess(lhs.lower_bounds, rhs.lower_bounds)) {
                    return true;
                } else if (lexLess(rhs.lower_bounds, lhs.lower_bounds)) {
                    return false;
                } else if (lexLess(lhs.upper_bounds, rhs.upper_bounds)) {
                    return true;
                }
                return false;
            }
        };

        struct UniquenessSetComparator {
            UniquenessHyperrectangleComparator hyperrect_comp = UniquenessHyperrectangleComparator{};

            bool operator()(const Set& lhs, const Set& rhs) const {
                if (lhs.first < rhs.first) {
                    return true;
                } else if (rhs.first < lhs.first) {
                    return false;
                } 
                return hyperrect_comp(lhs.second, rhs.second);
            }
        };

        /// @brief State comparison for uniqueness
        struct UniquenessStateComparator {
            BRY_INL bool operator()(const State& lhs, const State& rhs) const {
                UniquenessQSetItComparator comp;
                return std::lexicographical_compare(lhs.sets.begin(), lhs.sets.end(), 
                                                    rhs.sets.begin(), rhs.sets.end(), comp);
            }
        };

        /// @brief Sort by greatest robustness first for DFS
        struct RobustnessStateComparator {
            BRY_INL bool operator()(const State* lhs, const State* rhs) const {
                return lhs->min_robustness > rhs->min_robustness;
            }
        };

    private:
        /// @brief Run the search algorithm and compute the best state
        /// @return Non-owning pointer to the max-min-robustness state found
        const State* search(); 

        /// @brief Check if a set is unique, if so insert it and return its pointer
        /// @param set Set to insert
        std::pair<QSetIt, bool> insertUniqueSet(Set&& set);

        /// @brief Generate the next states and add them to `m_unique_states`
        /// @param curr_state State to apply the actions to
        /// @param actions Actions to apply
        void expandState(const State* curr_state, const std::vector<Action<DIM>*>& actions);

        void proposeSolutionState(const State* state);

        void calculateRobustness(const Set& set, SetProperties& properties);

        std::string ctToStr(ConstraintType type) const {
            switch (type) {
                case ConstraintType::Workspace:
                    return "Wksp";
                case ConstraintType::Init:
                    return "Init";
                case ConstraintType::Unsafe:
                    return "Unsf";
                case ConstraintType::Safe:
                    return "Safe";
            }
            return std::string();
        }
        void printSet(const QSetIt& qset) const {
            const Set& set = qset->first;
            const SetProperties& properties = qset->second;
            if (!properties.vertex_condition) {
                std::cout << "Set type: " << ctToStr(set.first);
                std::cout << " l[" << std::setw(14) << set.second.lower_bounds[0] << ", " << std::setw(14) << set.second.lower_bounds[1] << "] ";
                std::cout << " u[" << std::setw(14) << set.second.upper_bounds[0] << ", " << std::setw(14) << set.second.upper_bounds[1] << "] ";
                std::cout << " rob: " << std::setw(14) << properties.min_robustness;
                //if (properties.vertex_condition) {
                //    std::cout << " VC";
                //}
                std::cout << "\n";

            }
        }

    private:

        /* Cached things used multiple times throughout the search */

        Vector m_soln_vec;
        Matrix m_F_expec_Gamma;
        Matrix m_deg_lift_tf;

        /* Search-related members */

        /// @brief Container holding all unique sets and their properties to avoid duplicates
        std::map<Set, SetProperties, UniquenessSetComparator> m_unique_sets;

        /// @brief Container holding all unique states encountered during search. 
        std::set<State, UniquenessStateComparator> m_unique_states;

        /// @brief Set that orders the states that have not been expanded according to DFS objective
        std::multiset<const State*, RobustnessStateComparator> m_expansion_set;
        //std::list<const State*> m_expansion_set;

        bry_int_t m_solution_states_encountered = 0;
        const State* m_solution_state = nullptr;

};

}

#include "impl/AdaptiveProblem_impl.hpp"